---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for SLES for SAP servers
    zypper:
      name: 
        - apache2
        - php8
      state: latest
      update_cache: true
    when: ansible_distribution == "SLES_SAP"

  - name: install apache and php for RHEL servers
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: true
    when: ansible_distribution == "RedHat"
